### ISSUE TITLE
Fix launching puppeteer browser on Heroku

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#354]
I've tried to generate Process.st URL:

Logs:
```
2021-09-15T14:42:33.932310+00:00 heroku[router]: at=info method=POST path="/api/learning-materials" host=coderscamp-staging.herokuapp.com request_id=f0cec4a2-8caa-44e6-9a25-4049f3d88f8b fwd="78.11.22.210" dyno=web.1 connect=0ms service=22ms status=500 bytes=278 protocol=https
2021-09-15T14:42:34.091803+00:00 app[web.1]: [31m[Nest] 38  - [39m09/15/2021, 2:42:34 PM [31m  ERROR[39m [38;5;3m[ExceptionsHandler] [39m[31mFailed to launch the browser process!
2021-09-15T14:42:34.091810+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
2021-09-15T14:42:34.091811+00:00 app[web.1]: 
2021-09-15T14:42:34.091811+00:00 app[web.1]: 
2021-09-15T14:42:34.091813+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2021-09-15T14:42:34.091813+00:00 app[web.1]: [39m
2021-09-15T14:42:34.091880+00:00 app[web.1]: Error: Failed to launch the browser process!
2021-09-15T14:42:34.091881+00:00 app[web.1]: /app/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
2021-09-15T14:42:34.091881+00:00 app[web.1]: 
2021-09-15T14:42:34.091881+00:00 app[web.1]: 
2021-09-15T14:42:34.091881+00:00 app[web.1]: TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
2021-09-15T14:42:34.091882+00:00 app[web.1]: 
2021-09-15T14:42:34.091882+00:00 app[web.1]:     at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
2021-09-15T14:42:34.091882+00:00 app[web.1]:     at Interface.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
2021-09-15T14:42:34.091883+00:00 app[web.1]:     at Interface.emit (events.js:412:35)
2021-09-15T14:42:34.091883+00:00 app[web.1]:     at Interface.close (readline.js:451:8)
2021-09-15T14:42:34.091883+00:00 app[web.1]:     at Socket.onend (readline.js:224:10)
2021-09-15T14:42:34.091883+00:00 app[web.1]:     at Socket.emit (events.js:412:35)
2021-09-15T14:42:34.091884+00:00 app[web.1]:     at endReadableNT (internal/streams/readable.js:1317:12)
2021-09-15T14:42:34.091885+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Comment by nowakprojects** [comment]
@KonradSzwarc any ideas what may be wrong on Heroku?

**Comment by nowakprojects** [comment]
https://stackoverflow.com/questions/48009016/error-while-excuting-chrome-without-headless-on-heroku
