### ISSUE TITLE
Fix tests on main branch - user registration

### ISSUE THREAD

**Issue by nowakprojects** [CodersCrew/coderscamp#368]
https://github.com/CodersCrew/coderscamp/runs/3656554604

LOGS:
```.ts
  Invalid `prisma.eventsSubscription.upsert()` invocation:


      Unique constraint failed on the fields: (`id`)

      240 |
      241 |   private async moveCurrentPosition(position: number, transaction: PrismaTransactionManager) {
    > 242 |     await transaction.eventsSubscription.upsert({
          |     ^
      243 |       where: {
      244 |         id: this.subscriptionId,
      245 |       },

      at cb (../../node_modules/@prisma/client/runtime/index.js:36940:17)
      at EventsSubscription.moveCurrentPosition (src/module/write/shared/application/events-subscription/events-subscription.ts:242:5)
      at EventsSubscription.handleEvent (src/module/write/shared/application/events-subscription/events-subscription.ts:199:7)
      at EventsSubscription.listen (src/module/write/shared/application/events-subscription/events-subscription.ts:143:9)

```

**Comment by nowakprojects** [comment]
@htk4 Could you take a look? Do you have any idea what it's the cause of this issue?

**Comment by htk4** [comment]
I don't know why?, but it seems that [this](https://github.com/CodersCrew/coderscamp/pull/369/files#diff-88bf2002f1ec79b60279eb29f4a1b44436b290fc17f829d33e9306eb9271355bR21-R24) fixes issue.
```js
afterEach(async () => {
    await module.close();
});
```
